// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../mocks/brokers/kafka.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	kafka "github.com/segmentio/kafka-go"
	gomock "go.uber.org/mock/gomock"
)

// MockITopicCreator is a mock of ITopicCreator interface.
type MockITopicCreator struct {
	ctrl     *gomock.Controller
	recorder *MockITopicCreatorMockRecorder
	isgomock struct{}
}

// MockITopicCreatorMockRecorder is the mock recorder for MockITopicCreator.
type MockITopicCreatorMockRecorder struct {
	mock *MockITopicCreator
}

// NewMockITopicCreator creates a new mock instance.
func NewMockITopicCreator(ctrl *gomock.Controller) *MockITopicCreator {
	mock := &MockITopicCreator{ctrl: ctrl}
	mock.recorder = &MockITopicCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITopicCreator) EXPECT() *MockITopicCreatorMockRecorder {
	return m.recorder
}

// CreateTopics mocks base method.
func (m *MockITopicCreator) CreateTopics(arg0 context.Context, arg1 *kafka.CreateTopicsRequest) (*kafka.CreateTopicsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopics", arg0, arg1)
	ret0, _ := ret[0].(*kafka.CreateTopicsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTopics indicates an expected call of CreateTopics.
func (mr *MockITopicCreatorMockRecorder) CreateTopics(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopics", reflect.TypeOf((*MockITopicCreator)(nil).CreateTopics), arg0, arg1)
}
