// Code generated by MockGen. DO NOT EDIT.
// Source: intefrace.go
//
// Generated by this command:
//
//	mockgen -source=intefrace.go -destination=../../../mocks/cache/exchangeRateCache.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	core "github.com/kVinsom/Bank-exhange-rate-service/pkg/core"
	gomock "go.uber.org/mock/gomock"
)

// MockIExchangeRateCache is a mock of IExchangeRateCache interface.
type MockIExchangeRateCache struct {
	ctrl     *gomock.Controller
	recorder *MockIExchangeRateCacheMockRecorder
	isgomock struct{}
}

// MockIExchangeRateCacheMockRecorder is the mock recorder for MockIExchangeRateCache.
type MockIExchangeRateCacheMockRecorder struct {
	mock *MockIExchangeRateCache
}

// NewMockIExchangeRateCache creates a new mock instance.
func NewMockIExchangeRateCache(ctrl *gomock.Controller) *MockIExchangeRateCache {
	mock := &MockIExchangeRateCache{ctrl: ctrl}
	mock.recorder = &MockIExchangeRateCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIExchangeRateCache) EXPECT() *MockIExchangeRateCacheMockRecorder {
	return m.recorder
}

// AddAllExchangeRate mocks base method.
func (m *MockIExchangeRateCache) AddAllExchangeRate(ctx context.Context, rates []core.Ranking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAllExchangeRate", ctx, rates)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAllExchangeRate indicates an expected call of AddAllExchangeRate.
func (mr *MockIExchangeRateCacheMockRecorder) AddAllExchangeRate(ctx, rates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAllExchangeRate", reflect.TypeOf((*MockIExchangeRateCache)(nil).AddAllExchangeRate), ctx, rates)
}

// GetAllExchangeRate mocks base method.
func (m *MockIExchangeRateCache) GetAllExchangeRate(ctx context.Context, currencyIsoFrom int32) ([]core.Ranking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllExchangeRate", ctx, currencyIsoFrom)
	ret0, _ := ret[0].([]core.Ranking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllExchangeRate indicates an expected call of GetAllExchangeRate.
func (mr *MockIExchangeRateCacheMockRecorder) GetAllExchangeRate(ctx, currencyIsoFrom any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllExchangeRate", reflect.TypeOf((*MockIExchangeRateCache)(nil).GetAllExchangeRate), ctx, currencyIsoFrom)
}

// GetExchangeRate mocks base method.
func (m *MockIExchangeRateCache) GetExchangeRate(ctx context.Context, currencyIsoFrom, currencyIsoTo int32) (*core.Ranking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExchangeRate", ctx, currencyIsoFrom, currencyIsoTo)
	ret0, _ := ret[0].(*core.Ranking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExchangeRate indicates an expected call of GetExchangeRate.
func (mr *MockIExchangeRateCacheMockRecorder) GetExchangeRate(ctx, currencyIsoFrom, currencyIsoTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExchangeRate", reflect.TypeOf((*MockIExchangeRateCache)(nil).GetExchangeRate), ctx, currencyIsoFrom, currencyIsoTo)
}
