// Code generated by MockGen. DO NOT EDIT.
// Source: interface_service.go
//
// Generated by this command:
//
//	mockgen -source=interface_service.go -destination=../../../internal/mocks/services/exchangeRate.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	exchange_rate "github.com/Suinar/Bank-proto/exchange_rate"
	gomock "go.uber.org/mock/gomock"
)

// MockIExchangeRateService is a mock of IExchangeRateService interface.
type MockIExchangeRateService struct {
	ctrl     *gomock.Controller
	recorder *MockIExchangeRateServiceMockRecorder
	isgomock struct{}
}

// MockIExchangeRateServiceMockRecorder is the mock recorder for MockIExchangeRateService.
type MockIExchangeRateServiceMockRecorder struct {
	mock *MockIExchangeRateService
}

// NewMockIExchangeRateService creates a new mock instance.
func NewMockIExchangeRateService(ctrl *gomock.Controller) *MockIExchangeRateService {
	mock := &MockIExchangeRateService{ctrl: ctrl}
	mock.recorder = &MockIExchangeRateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIExchangeRateService) EXPECT() *MockIExchangeRateServiceMockRecorder {
	return m.recorder
}

// GetAllExchangeRate mocks base method.
func (m *MockIExchangeRateService) GetAllExchangeRate(ctx context.Context, currencyIdFrom int64) (*exchange_rate.RankingList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllExchangeRate", ctx, currencyIdFrom)
	ret0, _ := ret[0].(*exchange_rate.RankingList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllExchangeRate indicates an expected call of GetAllExchangeRate.
func (mr *MockIExchangeRateServiceMockRecorder) GetAllExchangeRate(ctx, currencyIdFrom any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllExchangeRate", reflect.TypeOf((*MockIExchangeRateService)(nil).GetAllExchangeRate), ctx, currencyIdFrom)
}

// GetExchangeRate mocks base method.
func (m *MockIExchangeRateService) GetExchangeRate(ctx context.Context, currencyIdFrom, currencyIdTo int64) (*exchange_rate.RankingList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExchangeRate", ctx, currencyIdFrom, currencyIdTo)
	ret0, _ := ret[0].(*exchange_rate.RankingList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExchangeRate indicates an expected call of GetExchangeRate.
func (mr *MockIExchangeRateServiceMockRecorder) GetExchangeRate(ctx, currencyIdFrom, currencyIdTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExchangeRate", reflect.TypeOf((*MockIExchangeRateService)(nil).GetExchangeRate), ctx, currencyIdFrom, currencyIdTo)
}
